### ISSUE TITLE
A possibility to indicate services+chars handle numbers; default services as option ?

### ISSUE THREAD

**Issue by jslawek** [sandeepmistry/bleno#224]
Hi,
In my project, I simulate existing peripheral device using bleno.
My purpose is to trick mobile application in connecting to such simulated device instead original one. For that, I usually need to clone MAC address. And because mobile OS-es implement GATT cache (based on MAC address), the simulated device's handle numbers need to be exactly matched. Otherwise the mobile app often does not work correctly, as it tries to issue GATT requests to different handles.
That is why I needed to specify the raw handle numbers while setting services+characteristics.
I also had to remove the automatically filled by bleno services 1800 and 1801, as I provide them myself with different values. My version of bleno's lib/hci-socket/gatt.js setServices is available here:

https://github.com/securing/gattacker/blob/8cc7ae5939641c97a49c5f568bf8a07783ce82ec/lib/bleno/lib/hci-socket/gatt.js#L263-L388

I am aware you are not keen on using raw handles. And I am not sure if that would be possible in Mac. But if you would you consider such functionality (possibility to specify raw handle numbers, setting the default services as option), I could try to write a PR.

Or, if you would be able to point to a different solution/wrapper around bleno?

I know several others have struggled with this problem. Damien Cauquil has written a wrapper for internal bleno objects, but AFAIK it does not work stable enough:

https://github.com/DigitalSecurity/btlejuice/blob/c4823b85ff8e0276a0704eb50d1c10260667050c/fake.js#L226-#L329

**Comment by sandeepmistry** [comment]
Hi @jslawek,

There was some decision around this in https://github.com/sandeepmistry/bleno/pull/88.

>  I am not sure if that would be possible in Mac. 

It's not possible. So for cross-platform compatibility I'm not keen on adding this.

> Or, if you would be able to point to a different solution/wrapper around bleno?

Maybe we can split bleno into smaller reusable pieces? It seems like you want to use some pieces of bleno but customize or arrange them in a different way. Please start another issue thread to discuss this further along with a proposal.

The goal of this project is for a cross-platform BLE peripheral library, so that apps based on bleno can run on both OS X and Linux with the same API + behaviour.
