### ISSUE TITLE
Linux kernel 3.6

### ISSUE THREAD

**Issue by gtalusan** [sandeepmistry/bleno#298]
I noticed the documentation says Linux kernel 3.6.  What specifically about blend requires 3.6 and above?

**Comment by DanielTimLee** [comment]
guess `Bluez` has dependency on Kernel 3.4 or above.

Especially with BLE support, 3.5 is needed

> With this release BlueZ only supports the new Bluetooth Management kernel interface that was introduced in Linux 3.4, so essentially this is the minimum kernel requirement for BlueZ 5. For Low Energy support at least kernel version 3.5 is needed.

http://www.bluez.org/release-of-bluez-5-0/

**Comment by sandeepmistry** [comment]
@gtalusan I think this was a requirement because older versions used L2CAP kernel sockets. Now HCI sockets are used, so this may no longer be a requirement.

I don't have a Linux kernel system with older than 3.6 to test, but it would be great if you could test it out and submit a PR to remove the requirement.
