### ISSUE TITLE
bleno advertising not working after noble peripheral disconnect

### ISSUE THREAD

**Issue by remydavid** [sandeepmistry/bleno#64]
Trying to use bleno for BLE broadcasting just after disconnecting from a peripheral won't work.

We want to scan and connect to a peripheral while broadcasting BLE packets using the same adapter. 
Since it doesn't seems possible, we do : 
1) broadcast using bleno.startXXXAdvertising and listen using noble.startScanning
2) once peripheral is discovered, stop advertising with bleno.stopAdvertising
3) do something with the peripheral
4) disconnect using noble peripheral.disconnect()
5) restart broadcasting using bleno.startXXXAdvertising 

Step 5 don't thow an error but doesn't actually resume broadcast.

I have a small test program here :
https://gist.github.com/remydavid/d3d2cec640d290e2ca44
Tested on 2 linux box with 2 different BLE adapters (bleno 0.1.5, node v0.10.30, BlueZ 5.21)

**Comment by endoplasmic** [comment]
@remydavid are you able to share what you did to get noble and bleno running on the same Linux box? I've found myself in a scenario where I need to advertise on the same box as the central (since the phone will also be a central and a peripheral).

Did you need to create a new node process for the bleno client vs. the noble client (so the requires weren't shared) or were you able to manage to be in a scenario where you could require both modules in the same script?

Thanks a lot in advance :D
