### ISSUE TITLE
Any solutions working on Edison ?

### ISSUE THREAD

**Issue by danki** [sandeepmistry/bleno#84]
Am desperately trying to get Bleno working on Edison but i saw somewhere the bluetoothd messes Bleno up.

Is there any solutions out there that are working ?

**Comment by adageable** [comment]
Any further results on this from the intel Edison side?  I've been trying to follow the same steps as detailed in a previous comment (So far I can get Bluetooth LE running: http://rexstjohn.com/configure-intel-edison-for-bluetooth-le-smart-development/#more-2958), however, I'm not seeing any effect running the commands:

rfkill unblock bluetooth
killall bluetoothd
hciconfig hci0 up

Regardless, after execution, my beacon is briefly detected, then drops out as described in the steps prior to the workarounds above (basically, these workarounds appear to do nothing on my hardware, wasn't sure if anyone has seen similar issues.

**Comment by danki** [comment]
@adageable could you run following command on your edison and paste it back here:

```
root@sednew:~# npm show bleno | grep "version:" && opkg list-installed | grep bluez && uname -a && cat /etc/version && cat /etc/issue  
  version: '0.3.2',
bluez5 - 5.24-r0
bluez5-dev - 5.24-r0
bluez5-obex - 5.24-r0
pulseaudio-lib-bluez5-util - 5.0-r0
pulseaudio-module-bluez5-device - 5.0-r0
pulseaudio-module-bluez5-discover - 5.0-r0
Linux sednew 3.10.17-poky-edison+ #1 SMP PREEMPT Wed Apr 29 03:54:01 CEST 2015 i686 GNU/Linux
weekly-146
Poky (Yocto Project Reference Distro) 1.6.1 \n \l
```

**Comment by adageable** [comment]
Couple of notes here:

(0) Thanks for replying!

(1) I'm running this through the Intel IoT XDK / Studio... so I'm not 100% clear if the package management works the same (I ran the bluetooth code from IoT studio and received much the same result, however, as trying the Url from Rex St. John (I ran it both ways, with the same result, I believe).  I've since repeated the test following all of the instructions from http://rexstjohn.com/configure-intel-edison-for-bluetooth-le-smart-development/#more-2958

(2) Results from your queries
^Croot@edison1:/# npm show bleno | grep "version:" && opkg list-installed | grep bluez && uname -a && cat /etc/version && cat /etc/issue                                    
  version: '0.3.2',                                                                                                                                                         
bluez5 - 5.24-r0                                                                                                                                                            
bluez5-dev - 5.24-r0                                                                                                                                                        
bluez5-obex - 5.24-r0                                                                                                                                                       
pulseaudio-lib-bluez5-util - 6.0-r0                                                                                                                                         
pulseaudio-module-bluez5-device - 6.0-r0                                                                                                                                    
pulseaudio-module-bluez5-discover - 6.0-r0                                                                                                                                  
Linux edison1 3.10.17-poky-edison+ #1 SMP PREEMPT Fri Jun 19 12:06:40 CEST 2015 i686 GNU/Linux                                                                              
weekly-159.devkit-2.0                                                                                                                                                       
Poky (Yocto Project Reference Distro) 1.7.2 \n \l                                                                                                                           
                                                                                                                                                                            
root@edison1:/# node --version && npm --version                                                                                                                             
v0.10.38                                                                                                                                                                    
1.4.28

**Comment by danki** [comment]
@adageable thanks for posting dumps.
Now i see you use poky 1.7.2, that is the ww25 edison image. I did use that too here few weeks till about 4 days ago. Im not really sure what is going on, but BLE didnt work for me at all in ww25 image.

So my best recommendation for you would be, go back to ww18 (weekly 146).

When looking at "weekly-159.devkit-2.0" i would guess it is some kind of dev / nightly build. Havent found any docs on what has been changed in that particular build.
For example, configure_edison --setup is now gone there, instead one would just run configure_edison.

So yeah, go back to 146 and you should be fine there.

**Comment by adageable** [comment]
Interesting... looks like the BLE stack and the edison images aren't as stable as I hoped.  I will try the downgrade and post the results here just for verification (in a few days, unfortunately, as I'm caught up in other work).

Any ideas for contacts within the Edison community to escalate these issues with the images? I downloaded and attempted to run a very similar bluetooth demo directly from the Intel IoT studio, and the out of the box sample demo shows the same behavior (I'm assuming for the same reasons).  You can have a  bluetooth beacon if you want, but only for a few seconds!

Thanks for taking the time to help!

**Comment by danki** [comment]
Yeah i think its safer for you to go with ww18 (weekly-146) as i belive ww25 is some pre- or alpha release for developers to test and adapt code for.
Not really sure what Intel has changed in ww25, seems bluez is still at 5.24, but why BLE app behaviors are so different is kind of a mystery to me.

I would definitely flag the issues on Intel Edison forums but since 2014-nov i have not been able to log in to forums for some reason, tested with all kinds of browsers... nothing. Tho seems few peeps have flagged ww25 on forums to be un-safe for **production** usage. Lets hope intel puts together a decent page for tracking Edison related news and updates, current ones are just horrible :/

**Comment by sandeepmistry** [comment]
@danki good to ww25 is not stable, maybe that's why 146 is the latest via ```configure_edison```. @rexstjohn any comments on this?
